/**
 * Every word the controls show, per language, as the attributes each
 * control takes. English is the element's default and needs no attribute;
 * the rest are a set of them, which is all a language is to the element.
 * The order of the controls never changes with the language: a page that
 * wants a mirrored bar for Arabic writes it mirrored.
 */

export interface Words {
  readonly play: string;
  readonly pause: string;
  readonly replay: string;
  readonly mute: string;
  readonly unmute: string;
  readonly volume: string;
  readonly seek: string;
  /** With `{current}` and `{duration}`. */
  readonly of: string;
  /** With `{time}`. */
  readonly behind: string;
  readonly live: string;
  readonly goLive: string;
  readonly atEdge: string;
  readonly speed: string;
  readonly normal: string;
  /** With `{page}`. */
  readonly back: string;
  readonly quality: string;
  readonly auto: string;
  readonly audio: string;
  readonly subtitles: string;
  readonly off: string;
  readonly track: string;
  readonly settings: string;
  readonly size: string;
  readonly background: string;
  readonly small: string;
  readonly medium: string;
  readonly large: string;
  readonly xlarge: string;
  readonly none: string;
  readonly dark: string;
  readonly solid: string;
  /** With `{system}` and `{keys}`. */
  readonly protectedBy: string;
  /** With `{count}` and `{statuses}`. */
  readonly key: string;
  readonly keys: string;
  readonly noKey: string;
  readonly pipEnter: string;
  readonly pipExit: string;
  readonly fsEnter: string;
  readonly fsExit: string;
  readonly errorTitle: string;
  readonly retry: string;
  /** With `{seconds}`. */
  readonly skipBack: string;
  readonly skipForward: string;
}

export interface Language {
  readonly name: string;
  readonly words: Words;
}

export const LANGUAGES: Readonly<Record<string, Language>> = {
  ca: {
    name: 'Català',
    words: {
      play: 'Reproduir',
      pause: 'Pausa',
      replay: 'Torna a reproduir',
      mute: 'Silencia',
      unmute: 'Activa el so',
      volume: 'Volum',
      seek: 'Cerca',
      of: '{current} de {duration}',
      behind: '{time} darrere del directe',
      live: 'DIRECTE',
      goLive: 'Ves al directe',
      atEdge: 'Al directe',
      speed: 'Velocitat',
      normal: 'Normal',
      back: 'Torna de {page}',
      quality: 'Qualitat',
      auto: 'Automàtica',
      audio: 'Àudio',
      subtitles: 'Subtítols',
      off: 'Cap',
      track: 'Pista',
      settings: 'Opcions',
      size: 'Mida',
      background: 'Fons',
      small: 'Petita',
      medium: 'Mitjana',
      large: 'Gran',
      xlarge: 'Molt gran',
      none: 'Cap',
      dark: 'Fosc',
      solid: 'Sòlid',
      protectedBy: 'Protegit per {system}, {keys}',
      key: '{count} clau: {statuses}',
      keys: '{count} claus: {statuses}',
      noKey: 'cap clau encara',
      pipEnter: 'Imatge dins la imatge',
      pipExit: 'Surt de la imatge dins la imatge',
      fsEnter: 'Pantalla completa',
      fsExit: 'Surt de la pantalla completa',
      errorTitle: 'Error de reproducció',
      retry: 'Torna-ho a provar',
      skipBack: 'Enrere {seconds} segons',
      skipForward: 'Endavant {seconds} segons',
    },
  },
  es: {
    name: 'Español',
    words: {
      play: 'Reproducir',
      pause: 'Pausa',
      replay: 'Volver a reproducir',
      mute: 'Silenciar',
      unmute: 'Activar el sonido',
      volume: 'Volumen',
      seek: 'Buscar',
      of: '{current} de {duration}',
      behind: '{time} por detrás del directo',
      live: 'DIRECTO',
      goLive: 'Ir al directo',
      atEdge: 'En directo',
      speed: 'Velocidad',
      normal: 'Normal',
      back: 'Volver de {page}',
      quality: 'Calidad',
      auto: 'Automática',
      audio: 'Audio',
      subtitles: 'Subtítulos',
      off: 'Desactivados',
      track: 'Pista',
      settings: 'Ajustes',
      size: 'Tamaño',
      background: 'Fondo',
      small: 'Pequeño',
      medium: 'Mediano',
      large: 'Grande',
      xlarge: 'Muy grande',
      none: 'Ninguno',
      dark: 'Oscuro',
      solid: 'Sólido',
      protectedBy: 'Protegido por {system}, {keys}',
      key: '{count} clave: {statuses}',
      keys: '{count} claves: {statuses}',
      noKey: 'sin clave todavía',
      pipEnter: 'Imagen en imagen',
      pipExit: 'Salir de imagen en imagen',
      fsEnter: 'Pantalla completa',
      fsExit: 'Salir de pantalla completa',
      errorTitle: 'Error de reproducción',
      retry: 'Reintentar',
      skipBack: 'Retroceder {seconds} segundos',
      skipForward: 'Avanzar {seconds} segundos',
    },
  },
  fr: {
    name: 'Français',
    words: {
      play: 'Lecture',
      pause: 'Pause',
      replay: 'Relire',
      mute: 'Couper le son',
      unmute: 'Rétablir le son',
      volume: 'Volume',
      seek: 'Position',
      of: '{current} sur {duration}',
      behind: '{time} derrière le direct',
      live: 'DIRECT',
      goLive: 'Aller au direct',
      atEdge: 'En direct',
      speed: 'Vitesse',
      normal: 'Normale',
      back: 'Retour depuis {page}',
      quality: 'Qualité',
      auto: 'Automatique',
      audio: 'Audio',
      subtitles: 'Sous-titres',
      off: 'Désactivés',
      track: 'Piste',
      settings: 'Réglages',
      size: 'Taille',
      background: 'Fond',
      small: 'Petite',
      medium: 'Moyenne',
      large: 'Grande',
      xlarge: 'Très grande',
      none: 'Aucun',
      dark: 'Sombre',
      solid: 'Opaque',
      protectedBy: 'Protégé par {system}, {keys}',
      key: '{count} clé : {statuses}',
      keys: '{count} clés : {statuses}',
      noKey: 'pas encore de clé',
      pipEnter: 'Image dans l’image',
      pipExit: 'Quitter l’image dans l’image',
      fsEnter: 'Plein écran',
      fsExit: 'Quitter le plein écran',
      errorTitle: 'Échec de la lecture',
      retry: 'Réessayer',
      skipBack: 'Reculer de {seconds} secondes',
      skipForward: 'Avancer de {seconds} secondes',
    },
  },
  de: {
    name: 'Deutsch',
    words: {
      play: 'Wiedergabe',
      pause: 'Pause',
      replay: 'Erneut abspielen',
      mute: 'Stummschalten',
      unmute: 'Ton einschalten',
      volume: 'Lautstärke',
      seek: 'Position',
      of: '{current} von {duration}',
      behind: '{time} hinter Live',
      live: 'LIVE',
      goLive: 'Zum Live-Bild',
      atEdge: 'Am Live-Bild',
      speed: 'Geschwindigkeit',
      normal: 'Normal',
      back: 'Zurück aus {page}',
      quality: 'Qualität',
      auto: 'Automatisch',
      audio: 'Audio',
      subtitles: 'Untertitel',
      off: 'Aus',
      track: 'Spur',
      settings: 'Einstellungen',
      size: 'Größe',
      background: 'Hintergrund',
      small: 'Klein',
      medium: 'Mittel',
      large: 'Groß',
      xlarge: 'Sehr groß',
      none: 'Keiner',
      dark: 'Dunkel',
      solid: 'Deckend',
      protectedBy: 'Geschützt durch {system}, {keys}',
      key: '{count} Schlüssel: {statuses}',
      keys: '{count} Schlüssel: {statuses}',
      noKey: 'noch kein Schlüssel',
      pipEnter: 'Bild im Bild',
      pipExit: 'Bild im Bild verlassen',
      fsEnter: 'Vollbild',
      fsExit: 'Vollbild verlassen',
      errorTitle: 'Wiedergabe fehlgeschlagen',
      retry: 'Erneut versuchen',
      skipBack: '{seconds} Sekunden zurück',
      skipForward: '{seconds} Sekunden vor',
    },
  },
  it: {
    name: 'Italiano',
    words: {
      play: 'Riproduci',
      pause: 'Pausa',
      replay: 'Riproduci di nuovo',
      mute: 'Disattiva audio',
      unmute: 'Attiva audio',
      volume: 'Volume',
      seek: 'Posizione',
      of: '{current} di {duration}',
      behind: '{time} dietro la diretta',
      live: 'DIRETTA',
      goLive: 'Vai alla diretta',
      atEdge: 'In diretta',
      speed: 'Velocità',
      normal: 'Normale',
      back: 'Torna da {page}',
      quality: 'Qualità',
      auto: 'Automatica',
      audio: 'Audio',
      subtitles: 'Sottotitoli',
      off: 'Disattivati',
      track: 'Traccia',
      settings: 'Impostazioni',
      size: 'Dimensione',
      background: 'Sfondo',
      small: 'Piccola',
      medium: 'Media',
      large: 'Grande',
      xlarge: 'Molto grande',
      none: 'Nessuno',
      dark: 'Scuro',
      solid: 'Pieno',
      protectedBy: 'Protetto da {system}, {keys}',
      key: '{count} chiave: {statuses}',
      keys: '{count} chiavi: {statuses}',
      noKey: 'nessuna chiave ancora',
      pipEnter: 'Immagine nell’immagine',
      pipExit: 'Esci da immagine nell’immagine',
      fsEnter: 'Schermo intero',
      fsExit: 'Esci da schermo intero',
      errorTitle: 'Riproduzione non riuscita',
      retry: 'Riprova',
      skipBack: 'Indietro di {seconds} secondi',
      skipForward: 'Avanti di {seconds} secondi',
    },
  },
  pt: {
    name: 'Português',
    words: {
      play: 'Reproduzir',
      pause: 'Pausar',
      replay: 'Reproduzir de novo',
      mute: 'Silenciar',
      unmute: 'Ativar o som',
      volume: 'Volume',
      seek: 'Posição',
      of: '{current} de {duration}',
      behind: '{time} atrás do direto',
      live: 'DIRETO',
      goLive: 'Ir para o direto',
      atEdge: 'Em direto',
      speed: 'Velocidade',
      normal: 'Normal',
      back: 'Voltar de {page}',
      quality: 'Qualidade',
      auto: 'Automática',
      audio: 'Áudio',
      subtitles: 'Legendas',
      off: 'Desligadas',
      track: 'Faixa',
      settings: 'Definições',
      size: 'Tamanho',
      background: 'Fundo',
      small: 'Pequeno',
      medium: 'Médio',
      large: 'Grande',
      xlarge: 'Muito grande',
      none: 'Nenhum',
      dark: 'Escuro',
      solid: 'Sólido',
      protectedBy: 'Protegido por {system}, {keys}',
      key: '{count} chave: {statuses}',
      keys: '{count} chaves: {statuses}',
      noKey: 'ainda sem chave',
      pipEnter: 'Imagem na imagem',
      pipExit: 'Sair de imagem na imagem',
      fsEnter: 'Ecrã inteiro',
      fsExit: 'Sair de ecrã inteiro',
      errorTitle: 'A reprodução falhou',
      retry: 'Tentar de novo',
      skipBack: 'Recuar {seconds} segundos',
      skipForward: 'Avançar {seconds} segundos',
    },
  },
  zh: {
    name: '中文',
    words: {
      play: '播放',
      pause: '暂停',
      replay: '重新播放',
      mute: '静音',
      unmute: '取消静音',
      volume: '音量',
      seek: '进度',
      of: '{current} / {duration}',
      behind: '落后直播 {time}',
      live: '直播',
      goLive: '跳到直播',
      atEdge: '正在直播',
      speed: '播放速度',
      normal: '正常',
      back: '从{page}返回',
      quality: '画质',
      auto: '自动',
      audio: '音轨',
      subtitles: '字幕',
      off: '关闭',
      track: '字幕轨',
      settings: '设置',
      size: '字号',
      background: '背景',
      small: '小',
      medium: '中',
      large: '大',
      xlarge: '特大',
      none: '无',
      dark: '深色',
      solid: '实色',
      protectedBy: '由 {system} 保护，{keys}',
      key: '{count} 个密钥：{statuses}',
      keys: '{count} 个密钥：{statuses}',
      noKey: '尚无密钥',
      pipEnter: '画中画',
      pipExit: '退出画中画',
      fsEnter: '全屏',
      fsExit: '退出全屏',
      errorTitle: '播放失败',
      retry: '重试',
      skipBack: '后退 {seconds} 秒',
      skipForward: '前进 {seconds} 秒',
    },
  },
  ja: {
    name: '日本語',
    words: {
      play: '再生',
      pause: '一時停止',
      replay: 'もう一度再生',
      mute: 'ミュート',
      unmute: 'ミュート解除',
      volume: '音量',
      seek: '再生位置',
      of: '{current} / {duration}',
      behind: 'ライブから {time} 遅れ',
      live: 'ライブ',
      goLive: 'ライブに移動',
      atEdge: 'ライブ中',
      speed: '再生速度',
      normal: '標準',
      back: '{page}から戻る',
      quality: '画質',
      auto: '自動',
      audio: '音声',
      subtitles: '字幕',
      off: 'オフ',
      track: 'トラック',
      settings: '設定',
      size: 'サイズ',
      background: '背景',
      small: '小',
      medium: '中',
      large: '大',
      xlarge: '特大',
      none: 'なし',
      dark: '暗い',
      solid: '不透明',
      protectedBy: '{system} で保護、{keys}',
      key: 'キー {count} 個: {statuses}',
      keys: 'キー {count} 個: {statuses}',
      noKey: 'キーはまだありません',
      pipEnter: 'ピクチャインピクチャ',
      pipExit: 'ピクチャインピクチャを終了',
      fsEnter: '全画面',
      fsExit: '全画面を終了',
      errorTitle: '再生に失敗しました',
      retry: '再試行',
      skipBack: '{seconds} 秒戻る',
      skipForward: '{seconds} 秒進む',
    },
  },
  ko: {
    name: '한국어',
    words: {
      play: '재생',
      pause: '일시정지',
      replay: '다시 재생',
      mute: '음소거',
      unmute: '음소거 해제',
      volume: '음량',
      seek: '재생 위치',
      of: '{current} / {duration}',
      behind: '실시간보다 {time} 뒤',
      live: '실시간',
      goLive: '실시간으로 이동',
      atEdge: '실시간 재생 중',
      speed: '재생 속도',
      normal: '보통',
      back: '{page}에서 돌아가기',
      quality: '화질',
      auto: '자동',
      audio: '오디오',
      subtitles: '자막',
      off: '끄기',
      track: '트랙',
      settings: '설정',
      size: '크기',
      background: '배경',
      small: '작게',
      medium: '보통',
      large: '크게',
      xlarge: '아주 크게',
      none: '없음',
      dark: '어둡게',
      solid: '불투명',
      protectedBy: '{system}(으)로 보호됨, {keys}',
      key: '키 {count}개: {statuses}',
      keys: '키 {count}개: {statuses}',
      noKey: '아직 키 없음',
      pipEnter: '화면 속 화면',
      pipExit: '화면 속 화면 종료',
      fsEnter: '전체 화면',
      fsExit: '전체 화면 종료',
      errorTitle: '재생에 실패했습니다',
      retry: '다시 시도',
      skipBack: '{seconds}초 뒤로',
      skipForward: '{seconds}초 앞으로',
    },
  },
  hi: {
    name: 'हिन्दी',
    words: {
      play: 'चलाएँ',
      pause: 'रोकें',
      replay: 'फिर से चलाएँ',
      mute: 'म्यूट करें',
      unmute: 'आवाज़ चालू करें',
      volume: 'आवाज़',
      seek: 'स्थिति',
      of: '{duration} में से {current}',
      behind: 'लाइव से {time} पीछे',
      live: 'लाइव',
      goLive: 'लाइव पर जाएँ',
      atEdge: 'लाइव पर',
      speed: 'गति',
      normal: 'सामान्य',
      back: '{page} से वापस',
      quality: 'गुणवत्ता',
      auto: 'स्वचालित',
      audio: 'ऑडियो',
      subtitles: 'उपशीर्षक',
      off: 'बंद',
      track: 'ट्रैक',
      settings: 'सेटिंग',
      size: 'आकार',
      background: 'पृष्ठभूमि',
      small: 'छोटा',
      medium: 'मध्यम',
      large: 'बड़ा',
      xlarge: 'बहुत बड़ा',
      none: 'कोई नहीं',
      dark: 'गहरा',
      solid: 'ठोस',
      protectedBy: '{system} द्वारा सुरक्षित, {keys}',
      key: '{count} कुंजी: {statuses}',
      keys: '{count} कुंजियाँ: {statuses}',
      noKey: 'अभी कोई कुंजी नहीं',
      pipEnter: 'पिक्चर इन पिक्चर',
      pipExit: 'पिक्चर इन पिक्चर से बाहर निकलें',
      fsEnter: 'पूर्ण स्क्रीन',
      fsExit: 'पूर्ण स्क्रीन से बाहर निकलें',
      errorTitle: 'प्लेबैक विफल रहा',
      retry: 'फिर से कोशिश करें',
      skipBack: '{seconds} सेकंड पीछे',
      skipForward: '{seconds} सेकंड आगे',
    },
  },
  ar: {
    name: 'العربية',
    words: {
      play: 'تشغيل',
      pause: 'إيقاف مؤقت',
      replay: 'إعادة التشغيل',
      mute: 'كتم الصوت',
      unmute: 'تشغيل الصوت',
      volume: 'مستوى الصوت',
      seek: 'الموضع',
      of: '{current} من {duration}',
      behind: 'متأخر عن البث المباشر بمقدار {time}',
      live: 'مباشر',
      goLive: 'الانتقال إلى البث المباشر',
      atEdge: 'في البث المباشر',
      speed: 'السرعة',
      normal: 'عادية',
      back: 'رجوع من {page}',
      quality: 'الجودة',
      auto: 'تلقائية',
      audio: 'الصوت',
      subtitles: 'الترجمة',
      off: 'إيقاف',
      track: 'المسار',
      settings: 'الإعدادات',
      size: 'الحجم',
      background: 'الخلفية',
      small: 'صغير',
      medium: 'متوسط',
      large: 'كبير',
      xlarge: 'كبير جدًا',
      none: 'بدون',
      dark: 'داكنة',
      solid: 'معتمة',
      protectedBy: 'محمي بواسطة {system}، {keys}',
      key: 'مفتاح واحد: {statuses}',
      keys: '{count} مفاتيح: {statuses}',
      noKey: 'لا يوجد مفتاح بعد',
      pipEnter: 'صورة داخل صورة',
      pipExit: 'الخروج من صورة داخل صورة',
      fsEnter: 'ملء الشاشة',
      fsExit: 'الخروج من ملء الشاشة',
      errorTitle: 'فشل التشغيل',
      retry: 'إعادة المحاولة',
      skipBack: 'الرجوع {seconds} ثانية',
      skipForward: 'التقدم {seconds} ثانية',
    },
  },
};

/** The attributes a control takes in a language, by its tag. */
export function attributesFor(tag: string, words: Words): Readonly<Record<string, string>> {
  switch (tag) {
    case 'mbx-start-button':
      return { 'label-play': words.play, 'label-replay': words.replay };
    case 'mbx-error-screen':
      return { 'label-title': words.errorTitle, 'label-retry': words.retry };
    case 'mbx-play-button':
      return { 'label-play': words.play, 'label-pause': words.pause, 'label-replay': words.replay };
    case 'mbx-mute-button':
      return { 'label-mute': words.mute, 'label-unmute': words.unmute };
    case 'mbx-volume-slider':
      return { label: words.volume };
    case 'mbx-seek-bar':
      return { label: words.seek, 'label-of': words.of, 'label-behind': words.behind };
    case 'mbx-live-button':
      return { text: words.live, 'label-live': words.goLive, 'label-at-edge': words.atEdge };
    case 'mbx-speed-menu':
      return { label: words.speed, 'label-normal': words.normal, 'label-back': words.back };
    case 'mbx-quality-menu':
      return { label: words.quality, 'label-auto': words.auto, 'label-back': words.back };
    case 'mbx-audio-menu':
      return { label: words.audio, 'label-back': words.back };
    case 'mbx-subtitles-menu':
      return {
        label: words.subtitles,
        'label-back': words.back,
        'label-off': words.off,
        'label-track': words.track,
        'label-settings': words.settings,
        'label-size': words.size,
        'label-background': words.background,
        'label-small': words.small,
        'label-medium': words.medium,
        'label-large': words.large,
        'label-xlarge': words.xlarge,
        'label-none': words.none,
        'label-dark': words.dark,
        'label-solid': words.solid,
      };
    case 'mbx-drm-badge':
      return {
        label: words.protectedBy,
        'label-key': words.key,
        'label-keys': words.keys,
        'label-no-key': words.noKey,
      };
    case 'mbx-pip-button':
      return { 'label-enter': words.pipEnter, 'label-exit': words.pipExit };
    case 'mbx-fullscreen-button':
      return { 'label-enter': words.fsEnter, 'label-exit': words.fsExit };
    default:
      return {};
  }
}
